version: 2

project_name: pgmi

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pgmi
    binary: pgmi
    main: ./cmd/pgmi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/vvka-141/pgmi/internal/cli.version={{.Version}}
      - -X github.com/vvka-141/pgmi/internal/cli.commit={{.ShortCommit}}
      - -X github.com/vvka-141/pgmi/internal/cli.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: vvka-141
    name: pgmi
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

brews:
  - name: pgmi
    repository:
      owner: vvka-141
      name: homebrew-pgmi
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: pgmi-bot
      email: bot@pgmi.dev
    directory: Formula
    homepage: "https://github.com/vvka-141/pgmi"
    description: "PostgreSQL-native execution fabric for humans and autonomous agents"
    license: "MPL-2.0"
    install: |
      bin.install "pgmi"
    test: |
      system "#{bin}/pgmi", "--version"

# Chocolatey disabled for now - requires Windows runner or choco CLI on Linux
# chocolateys:
#   - name: pgmi
#     owners: vvka-141
#     authors: Alexey Evlampiev
#     ...
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
