version: 2

project_name: pgmi

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pgmi
    binary: pgmi
    main: ./cmd/pgmi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: vvka-141
    name: pgmi
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

brews:
  - name: pgmi
    repository:
      owner: vvka-141
      name: homebrew-pgmi
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: pgmi-bot
      email: bot@pgmi.dev
    directory: Formula
    homepage: "https://github.com/vvka-141/pgmi"
    description: "PostgreSQL-native execution fabric for humans and autonomous agents"
    license: "MPL-2.0"
    install: |
      bin.install "pgmi"
    test: |
      system "#{bin}/pgmi", "--version"

chocolateys:
  - name: pgmi
    owners: vvka-141
    authors: Alexey Evlampiev
    project_url: "https://github.com/vvka-141/pgmi"
    license_url: "https://github.com/vvka-141/pgmi/blob/main/LICENSE"
    require_license_acceptance: false
    project_source_url: "https://github.com/vvka-141/pgmi"
    docs_url: "https://github.com/vvka-141/pgmi#readme"
    bug_tracker_url: "https://github.com/vvka-141/pgmi/issues"
    tags: "postgresql database deployment cli devops migration"
    summary: "PostgreSQL-native execution fabric"
    description: |
      pgmi is a PostgreSQL-native execution fabric and deployment tool.
      It uses a session-centric approach: loads SQL files and runtime
      parameters into PostgreSQL session-scoped temporary tables, then
      hands control to a user-provided deploy.sql script.
    release_notes: "https://github.com/vvka-141/pgmi/releases/tag/{{.Tag}}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
