version: 2

project_name: pgmi

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pgmi
    binary: pgmi
    main: ./cmd/pgmi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/vvka-141/pgmi/internal/cli.version={{.Version}}
      - -X github.com/vvka-141/pgmi/internal/cli.commit={{.ShortCommit}}
      - -X github.com/vvka-141/pgmi/internal/cli.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: New Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\(.+\))?\!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: vvka-141
    name: pgmi
  draft: false
  prerelease: auto
  name_template: "pgmi {{.Tag}}"
  header: |
    ## Quick Install

    **macOS / Linux (Homebrew):**
    ```
    brew install vvka-141/pgmi/pgmi
    ```

    **Debian / Ubuntu (APT):**
    ```
    curl -1sLf 'https://dl.cloudsmith.io/public/vvka-141/pgmi/setup.deb.sh' | sudo bash
    sudo apt install pgmi
    ```

    **Windows (Chocolatey):**
    ```
    choco install pgmi
    ```

    **Manual download:** grab the archive for your platform from the assets below.

    | Platform | amd64 | arm64 |
    |----------|-------|-------|
    | Linux | [tar.gz](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_linux_amd64.tar.gz) | [tar.gz](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_linux_arm64.tar.gz) |
    | macOS | [tar.gz](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_darwin_amd64.tar.gz) | [tar.gz](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_darwin_arm64.tar.gz) |
    | Windows | [zip](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_windows_amd64.zip) | [zip](https://github.com/vvka-141/pgmi/releases/download/{{.Tag}}/pgmi_{{.Version}}_windows_arm64.zip) |

    **Install manually after download:**

    Linux / macOS:
    ```
    tar xzf pgmi_*.tar.gz && sudo mv pgmi /usr/local/bin/
    ```

    Windows (PowerShell as Admin):
    ```
    Expand-Archive pgmi_*.zip -DestinationPath C:\Tools
    # Add C:\Tools to your PATH if not already present
    ```

  footer: |
    ---
    **Verify download integrity:**
    ```
    sha256sum -c checksums.txt
    ```

    **Full changelog**: https://github.com/vvka-141/pgmi/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: pgmi
    repository:
      owner: vvka-141
      name: homebrew-pgmi
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: pgmi-bot
      email: bot@pgmi.dev
    directory: Formula
    homepage: "https://github.com/vvka-141/pgmi"
    description: "PostgreSQL-native execution fabric for humans and autonomous agents"
    license: "MPL-2.0"
    install: |
      bin.install "pgmi"
    test: |
      system "#{bin}/pgmi", "--version"

nfpms:
  - id: pgmi
    package_name: pgmi
    vendor: vvka-141
    homepage: "https://github.com/vvka-141/pgmi"
    maintainer: "Alexey Evlampiev <alexey.evlampiev@gmail.com>"
    description: "PostgreSQL-native execution fabric for humans and autonomous agents"
    license: "MPL-2.0"
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/pgmi/LICENSE
      - src: README.md
        dst: /usr/share/doc/pgmi/README.md

publishers:
  - name: cloudsmith
    ids:
      - pgmi
    cmd: |
      cloudsmith push deb vvka-141/pgmi/any-distro/any-version {{ .ArtifactPath }}
    env:
      - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}
