package ai

import (
	"strings"
	"testing"
)

func generate(t *testing.T) PlannedFile {
	t.Helper()
	files, err := GenerateSetup("claude", Stamp{Version: "1.2.3", Source: ModulePath})
	if err != nil {
		t.Fatalf("GenerateSetup: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("expected 1 file, got %d", len(files))
	}
	return files[0]
}

func TestGenerateSetup_ClaudeSkill(t *testing.T) {
	f := generate(t)

	if f.RelPath != "pgmi/SKILL.md" {
		t.Errorf("RelPath = %q, want pgmi/SKILL.md", f.RelPath)
	}

	for _, want := range []string{
		"name: pgmi",
		"description:",
		"deploy.sql",
		"pgmi_plan_view",
		"CALL pgmi_test()",
		ModulePath,
	} {
		if !strings.Contains(f.Content, want) {
			t.Errorf("generated skill missing %q", want)
		}
	}

	if strings.Contains(f.Content, coreMarker) {
		t.Errorf("core marker %q was not substituted", coreMarker)
	}
}

func TestGenerateSetup_UnsupportedAssistant(t *testing.T) {
	if _, err := GenerateSetup("codex", Stamp{}); err == nil {
		t.Fatal("expected error for unsupported assistant")
	}
}

func TestParseManaged_RoundTrip(t *testing.T) {
	f := generate(t)
	m := ParseManaged(f.Content)

	if !m.HasStamp {
		t.Fatal("expected HasStamp")
	}
	if m.Edited() {
		t.Error("freshly generated file should not be reported as edited")
	}
	if m.Stamp.Version != "1.2.3" {
		t.Errorf("Stamp.Version = %q, want 1.2.3", m.Stamp.Version)
	}
	if m.Stamp.Source != ModulePath {
		t.Errorf("Stamp.Source = %q, want %q", m.Stamp.Source, ModulePath)
	}
}

func TestParseManaged_DetectsEditsAnywhere(t *testing.T) {
	f := generate(t)

	cases := map[string]string{
		"body edit":     strings.Replace(f.Content, "# pgmi", "# pgmi EDITED", 1),
		"trailing edit": f.Content + "\nappended\n",
		"no stamp":      "just some prose with no stamp\n",
	}
	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			if !ParseManaged(content).Edited() {
				t.Errorf("%s should be reported as edited", name)
			}
		})
	}
}

func TestParseManaged_StaleNotEdited(t *testing.T) {
	// A file generated by an older build: different body, but its own stamp is
	// internally consistent. It must read as not-edited (pristine) but its body
	// must differ from the current generation, so `check` flags it stale.
	old := RenderManaged("# pgmi\n\nold core body\n", Stamp{Version: "0.0.1", Source: ModulePath})
	m := ParseManaged(old)

	if m.Edited() {
		t.Error("a pristine older-version file must not read as edited")
	}
	current := generate(t)
	if m.Body == ParseManaged(current.Content).Body {
		t.Error("expected old body to differ from current generation")
	}
}

func TestAdapterFor(t *testing.T) {
	if _, err := AdapterFor("claude"); err != nil {
		t.Errorf("claude should be supported: %v", err)
	}
	if _, err := AdapterFor("nope"); err == nil {
		t.Error("expected error for unknown assistant")
	}
}
