package testgen

import (
	"fmt"
	"strings"
	"time"

	"github.com/vvka-141/pgmi/internal/testdiscovery"
	"github.com/vvka-141/pgmi/internal/testgen"
)

// Config configures the test script generator.
type Config struct {
	WithTransaction bool
	WithNotices     bool
	WithDebug       bool
	Callback        string // Custom callback function name, empty for no callback
}

// DefaultConfig returns a default configuration.
func DefaultConfig() Config {
	return Config{
		WithTransaction: true,
		WithNotices:     true,
		WithDebug:       false,
	}
}

// Result contains the generated script and metadata.
type Result struct {
	Script        string
	FixtureCount  int
	TestCount     int
	TeardownCount int
}

// Generator generates standalone SQL test scripts.
type Generator struct {
	config Config
}

// New creates a new Generator with the given configuration.
func New(config Config) *Generator {
	return &Generator{config: config}
}

// Generate creates a standalone SQL script from test steps.
func (g *Generator) Generate(steps []testdiscovery.TestScriptRow, sourcePath, filterPattern string) Result {
	var sb strings.Builder
	var fixtureCount, testCount, teardownCount int

	// Header
	sb.WriteString("-- Generated by pgmi test generate\n")
	sb.WriteString(fmt.Sprintf("-- Source: %s\n", sourcePath))
	sb.WriteString(fmt.Sprintf("-- Filter: %s\n", filterPattern))
	sb.WriteString(fmt.Sprintf("-- Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	if g.config.Callback != "" {
		sb.WriteString(fmt.Sprintf("-- Callback: %s\n", g.config.Callback))
	}
	sb.WriteString("\n")

	// If callback is specified, include type and stub definitions
	if g.config.Callback != "" {
		g.writeCallbackInfrastructure(&sb)
	}

	// Optional transaction wrapper
	if g.config.WithTransaction {
		sb.WriteString("BEGIN;\n\n")
	}

	ordinal := 0

	// Suite start callback
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("suite_start", nil, "", 0, 0))
		sb.WriteString("\n")
	}

	// Process each step
	for _, step := range steps {
		ordinal++
		switch step.StepType {
		case testdiscovery.StepTypeFixture:
			fixtureCount++
			g.writeFixtureWithCallback(&sb, step, ordinal)
		case testdiscovery.StepTypeTest:
			testCount++
			g.writeTestWithCallback(&sb, step, ordinal)
		case testdiscovery.StepTypeTeardown:
			teardownCount++
			g.writeTeardownWithCallback(&sb, step, ordinal)
		}
	}

	// Suite end callback
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("suite_end", nil, "", 0, ordinal))
		sb.WriteString("\n")
	}

	// Optional transaction rollback
	if g.config.WithTransaction {
		sb.WriteString("ROLLBACK;  -- Always rollback: tests don't persist\n\n")
	}

	// Summary footer
	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Summary: %d fixture(s), %d test(s), %d teardown(s)\n",
		fixtureCount, testCount, teardownCount))
	sb.WriteString(g.sectionSeparator())

	return Result{
		Script:        sb.String(),
		FixtureCount:  fixtureCount,
		TestCount:     testCount,
		TeardownCount: teardownCount,
	}
}

// writeCallbackInfrastructure writes the type and callback stub definitions.
func (g *Generator) writeCallbackInfrastructure(sb *strings.Builder) {
	sb.WriteString(g.sectionSeparator())
	sb.WriteString("-- Callback Infrastructure (for standalone execution)\n")
	sb.WriteString(g.sectionSeparator())
	sb.WriteString(`
CREATE TYPE pg_temp.pgmi_test_event AS (
    event       TEXT,
    path        TEXT,
    directory   TEXT,
    depth       INT,
    ordinal     INT,
    context     JSONB
);

`)
	sb.WriteString(fmt.Sprintf(`CREATE OR REPLACE FUNCTION %s(e pg_temp.pgmi_test_event)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    CASE e.event
        WHEN 'suite_start'    THEN RAISE NOTICE '[pgmi] Test suite started';
        WHEN 'suite_end'      THEN RAISE NOTICE '[pgmi] Test suite completed (%% steps)', e.ordinal;
        WHEN 'fixture_start'  THEN RAISE NOTICE '[pgmi] Fixture: %%', e.path;
        WHEN 'fixture_end'    THEN NULL;
        WHEN 'test_start'     THEN RAISE NOTICE '[pgmi] Test: %%', e.path;
        WHEN 'test_end'       THEN NULL;
        WHEN 'rollback'       THEN RAISE DEBUG '[pgmi] Rollback: %%', COALESCE(e.path, e.directory);
        WHEN 'teardown_start' THEN RAISE DEBUG '[pgmi] Teardown: %%', e.directory;
        WHEN 'teardown_end'   THEN NULL;
        ELSE NULL;
    END CASE;
END $$;

`, testgen.EscapeQualifiedName(g.config.Callback)))
}

// formatCallback generates a callback invocation SQL statement.
func (g *Generator) formatCallback(event string, path *string, dir string, depth, ordinal int) string {
	pathSQL := "NULL"
	if path != nil {
		pathSQL = pgQuoteLiteral(*path)
	}
	return fmt.Sprintf(
		"SELECT %s(ROW('%s', %s, %s, %d, %d, NULL)::pg_temp.pgmi_test_event);",
		testgen.EscapeQualifiedName(g.config.Callback), event, pathSQL, pgQuoteLiteral(dir), depth, ordinal,
	)
}

// writeFixtureWithCallback writes a fixture step with optional callback invocations.
func (g *Generator) writeFixtureWithCallback(sb *strings.Builder, step testdiscovery.TestScriptRow, ordinal int) {
	pathStr := "(no path)"
	if step.ScriptPath != nil {
		pathStr = *step.ScriptPath
	}

	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Fixture: %s\n", pathStr))
	sb.WriteString(g.sectionSeparator())

	// Callback: fixture_start
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("fixture_start", step.ScriptPath, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	} else if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Fixture: %%', %s; END $$;\n",
			pgQuoteLiteral(pathStr)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "SAVEPOINT") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Creating savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.ScriptSQL != nil {
		sb.WriteString("-- <embedded fixture content>\n")
		sb.WriteString(*step.ScriptSQL)
		if !strings.HasSuffix(*step.ScriptSQL, "\n") {
			sb.WriteString("\n")
		}
	}

	// Callback: fixture_end
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("fixture_end", step.ScriptPath, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
}

// writeTestWithCallback writes a test step with optional callback invocations.
func (g *Generator) writeTestWithCallback(sb *strings.Builder, step testdiscovery.TestScriptRow, ordinal int) {
	pathStr := "(no path)"
	if step.ScriptPath != nil {
		pathStr = *step.ScriptPath
	}

	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Test: %s\n", pathStr))
	sb.WriteString(g.sectionSeparator())

	// Callback: test_start
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("test_start", step.ScriptPath, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	} else if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Test: %%', %s; END $$;\n",
			pgQuoteLiteral(pathStr)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "SAVEPOINT") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Creating savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.ScriptSQL != nil {
		sb.WriteString("-- <embedded test content>\n")
		sb.WriteString(*step.ScriptSQL)
		if !strings.HasSuffix(*step.ScriptSQL, "\n") {
			sb.WriteString("\n")
		}
	}

	// Callback: test_end
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("test_end", step.ScriptPath, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	}

	if step.PostExec != nil {
		// Callback: rollback
		if g.config.Callback != "" {
			sb.WriteString(g.formatCallback("rollback", step.ScriptPath, step.Directory, step.Depth, ordinal))
			sb.WriteString("\n")
		} else if g.config.WithDebug && strings.Contains(*step.PostExec, "ROLLBACK TO") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Rolling back savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PostExec)
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
}

// writeTeardownWithCallback writes a teardown step with optional callback invocations.
func (g *Generator) writeTeardownWithCallback(sb *strings.Builder, step testdiscovery.TestScriptRow, ordinal int) {
	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Teardown: %s\n", step.Directory))
	sb.WriteString(g.sectionSeparator())

	// Callback: teardown_start
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("teardown_start", nil, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	} else if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Teardown: %%', %s; END $$;\n",
			pgQuoteLiteral(step.Directory)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "ROLLBACK TO") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Rolling back to entry savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(step.Directory)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.PostExec != nil {
		sb.WriteString(*step.PostExec)
		sb.WriteString("\n")
	}

	// Callback: teardown_end
	if g.config.Callback != "" {
		sb.WriteString(g.formatCallback("teardown_end", nil, step.Directory, step.Depth, ordinal))
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
}

func (g *Generator) sectionSeparator() string {
	return "-- " + strings.Repeat("=", 65) + "\n"
}

func pgQuoteLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
