package testgen

import (
	"fmt"
	"strings"
	"time"

	"github.com/vvka-141/pgmi/internal/testdiscovery"
)

// Config configures the test script generator.
type Config struct {
	WithTransaction bool
	WithNotices     bool
	WithDebug       bool
}

// DefaultConfig returns a default configuration.
func DefaultConfig() Config {
	return Config{
		WithTransaction: true,
		WithNotices:     true,
		WithDebug:       false,
	}
}

// Result contains the generated script and metadata.
type Result struct {
	Script        string
	FixtureCount  int
	TestCount     int
	TeardownCount int
}

// Generator generates standalone SQL test scripts.
type Generator struct {
	config Config
}

// New creates a new Generator with the given configuration.
func New(config Config) *Generator {
	return &Generator{config: config}
}

// Generate creates a standalone SQL script from test steps.
func (g *Generator) Generate(steps []testdiscovery.TestScriptRow, sourcePath, filterPattern string) Result {
	var sb strings.Builder
	var fixtureCount, testCount, teardownCount int

	// Header
	sb.WriteString("-- Generated by pgmi test generate\n")
	sb.WriteString(fmt.Sprintf("-- Source: %s\n", sourcePath))
	sb.WriteString(fmt.Sprintf("-- Filter: %s\n", filterPattern))
	sb.WriteString(fmt.Sprintf("-- Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("\n")

	// Optional transaction wrapper
	if g.config.WithTransaction {
		sb.WriteString("BEGIN;\n\n")
	}

	// Process each step
	for _, step := range steps {
		switch step.StepType {
		case "fixture":
			fixtureCount++
			g.writeFixture(&sb, step)
		case "test":
			testCount++
			g.writeTest(&sb, step)
		case "teardown":
			teardownCount++
			g.writeTeardown(&sb, step)
		}
	}

	// Optional transaction rollback
	if g.config.WithTransaction {
		sb.WriteString("ROLLBACK;  -- Always rollback: tests don't persist\n\n")
	}

	// Summary footer
	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Summary: %d fixture(s), %d test(s), %d teardown(s)\n",
		fixtureCount, testCount, teardownCount))
	sb.WriteString(g.sectionSeparator())

	return Result{
		Script:        sb.String(),
		FixtureCount:  fixtureCount,
		TestCount:     testCount,
		TeardownCount: teardownCount,
	}
}

func (g *Generator) writeFixture(sb *strings.Builder, step testdiscovery.TestScriptRow) {
	pathStr := "(no path)"
	if step.ScriptPath != nil {
		pathStr = *step.ScriptPath
	}

	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Fixture: %s\n", pathStr))
	sb.WriteString(g.sectionSeparator())

	if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Fixture: %%', %s; END $$;\n",
			pgQuoteLiteral(pathStr)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "SAVEPOINT") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Creating savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.ScriptSQL != nil {
		sb.WriteString("-- <embedded fixture content>\n")
		sb.WriteString(*step.ScriptSQL)
		if !strings.HasSuffix(*step.ScriptSQL, "\n") {
			sb.WriteString("\n")
		}
	}

	sb.WriteString("\n")
}

func (g *Generator) writeTest(sb *strings.Builder, step testdiscovery.TestScriptRow) {
	pathStr := "(no path)"
	if step.ScriptPath != nil {
		pathStr = *step.ScriptPath
	}

	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Test: %s\n", pathStr))
	sb.WriteString(g.sectionSeparator())

	if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Test: %%', %s; END $$;\n",
			pgQuoteLiteral(pathStr)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "SAVEPOINT") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Creating savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.ScriptSQL != nil {
		sb.WriteString("-- <embedded test content>\n")
		sb.WriteString(*step.ScriptSQL)
		if !strings.HasSuffix(*step.ScriptSQL, "\n") {
			sb.WriteString("\n")
		}
	}

	if step.PostExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PostExec, "ROLLBACK TO") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Rolling back savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(pathStr)))
		}
		sb.WriteString(*step.PostExec)
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
}

func (g *Generator) writeTeardown(sb *strings.Builder, step testdiscovery.TestScriptRow) {
	sb.WriteString(g.sectionSeparator())
	sb.WriteString(fmt.Sprintf("-- Teardown: %s\n", step.Directory))
	sb.WriteString(g.sectionSeparator())

	if g.config.WithNotices {
		sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE NOTICE 'Teardown: %%', %s; END $$;\n",
			pgQuoteLiteral(step.Directory)))
	}

	if step.PreExec != nil {
		if g.config.WithDebug && strings.Contains(*step.PreExec, "ROLLBACK TO") {
			sb.WriteString(fmt.Sprintf("DO $$ BEGIN RAISE DEBUG 'Rolling back to entry savepoint for: %%', %s; END $$;\n",
				pgQuoteLiteral(step.Directory)))
		}
		sb.WriteString(*step.PreExec)
		sb.WriteString("\n")
	}

	if step.PostExec != nil {
		sb.WriteString(*step.PostExec)
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
}

func (g *Generator) sectionSeparator() string {
	return "-- " + strings.Repeat("=", 65) + "\n"
}

func pgQuoteLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
